<?xml version="1.0"?>
<package format="3">
  <name>drone_planner</name>
  <version>0.1.0</version>
  <description>Obstacle-aware path planning and path following package.</description>
  <maintainer email="tang@example.com">Tang</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>

