position_controller_node:
  ros__parameters:
    position_gain:
    - 3.0
    - 3.0
    - 6.0
quadrotor_dynamics_node:
  ros__parameters:
    disturbance_amplitude_force_world:
    - 2.5
    - 0.625
    - 0.0
    disturbance_random_seed: 41
